version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ronald
      MONGO_INITDB_ROOT_PASSWORD: weston
  bot:
    build: bot/
    restart: always
    ports:
      - 40000:8080
